<%@ taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@ taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<%@ taglib uri="http://sakaiproject.org/jsf/sakai" prefix="sakai" %>
<%-- This file generated by Sakai App Builder --%>
<f:loadBundle basename="asignatura" var="msgs"/>

<f:view>
	<sakai:view_container title="Webasimaster Tool">
		<style type="text/css">
			@import url("/webasimaster/css/Webasimaster.css");
		</style>
		
		<sakai:view_content>
			<h:form id="asignaturas">
			 	<sakai:view_title value="#{msgs.asignatura_title}"/>

				<sakai:messages />

				<sakai:instruction_message value="#{msgs.asignatura_instr}"/>

			 	<h:dataTable
			 		id="asignaturalist"
			 		value="#{WebasimasterBean.asignaturas}"
			 		var="asignatura"
			 		columnClasses="firstColumn,secondColumn"
			 		headerClass="headerAlignment"
			 		styleClass="listHier">

					<h:column>
						<f:facet name="header">
							<h:outputText value="#{msgs.asignatura_code}"/>
						</f:facet>
						<f:verbatim><a href="</f:verbatim>
						<h:outputText value="#{asignatura.url}" />
						<f:verbatim>" onclick="javascript:parent.location.replace('</f:verbatim>
						<h:outputText value="#{asignatura.url}" />
						<f:verbatim>')"></f:verbatim>
						<h:outputText value="#{asignatura.code}" />
						<f:verbatim></a></f:verbatim>
					</h:column>

					<h:column>
						<f:facet name="header">
							<h:outputText value="#{msgs.asignatura_name}"/>
						</f:facet>
						<h:outputText value="#{asignatura.name}"/>
					</h:column>

				</h:dataTable>

				<h:outputText value="#{msgs.asignatura_nodefined}" rendered="#{WebasimasterBean.noHayDatos}"/>
				
			 </h:form>
  		</sakai:view_content>	
	</sakai:view_container>
</f:view> 
